### ISSUE TITLE
java.lang.IllegalArgumentException: Illegal group reference

### ISSUE THREAD

**Issue by liangxunchang** [cnescatlab/sonar-cnes-report#364] opened 2023-08-17 02:47 UTC
#### Describe the bug

when i use CNES Report, it show error "java.lang.IllegalArgumentException: Illegal group reference"
#### To reproduce

> _Steps to reproduce the behavior._

1. Go to 'More'
2. Click on 'CNES Report'
3. Choice my my projects

#### Screenshots & log
Aug 16, 2023 9:22:45 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube URL: http://sonar.odc.sunline.cn
Aug 16, 2023 9:22:46 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: SonarQube online: true
Aug 16, 2023 9:22:46 AM fr.cnes.sonar.report.ReportCommandLine execute
INFO: Detected SonarQube version: 8.9.10.61524
Aug 16, 2023 9:23:07 AM fr.cnes.sonar.report.exporters.docx.DocXExporter export
WARNING: Unable to find provided DOCX template file (using default one instead) : /opt/sonarqube/extensions/plugins/./template.docx
Aug 16, 2023 9:23:10 AM fr.cnes.sonar.report.ReportCommandLine main
SEVERE: Illegal group reference
java.lang.IllegalArgumentException: Illegal group reference
        at java.base/java.util.regex.Matcher.appendExpandedReplacement(Unknown Source)
        at java.base/java.util.regex.Matcher.appendReplacement(Unknown Source)
        at java.base/java.util.regex.Matcher.replaceAll(Unknown Source)
        at java.base/java.lang.String.replaceAll(Unknown Source)
        at fr.cnes.sonar.report.exporters.docx.DocXTools.replaceInParagraph(DocXTools.java:293)
        at fr.cnes.sonar.report.exporters.docx.DocXTools.replacePlaceholder(DocXTools.java:175)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.replaceSimplePlaceholders(DocXExporter.java:182)
        at fr.cnes.sonar.report.exporters.docx.DocXExporter.export(DocXExporter.java:156)
        at fr.cnes.sonar.report.factory.ReportFactory.report(ReportFactory.java:109)
        at fr.cnes.sonar.report.ReportCommandLine.execute(ReportCommandLine.java:147)
        at fr.cnes.sonar.report.ReportCommandLine.main(ReportCommandLine.java:82)
#### User environment 

> _Please complete the following information._

* sonarqube v8.9.10 Docker
* CNES Report Version 4.1.3

**Comment by Topin2001** [comment] 2024-06-06 09:52
Hi, to you still encounter this issue ?
From my side I cannot reproduce it, did you change something from the default plugin settings ?

**Comment by Topin2001** [comment] 2024-07-11 08:00
Without any reponse, I'm closing this issue, feel free to ask me to re-open it if you encounter this issue again

**Closed by Topin2001** 2024-07-11 08:00 UTC
Labels: bug
