### ISSUE TITLE
Cant generate report if project name contains special char

### ISSUE THREAD

**Issue by wilsade** [cnescatlab/sonar-cnes-report#107] opened 2020-01-09 12:06 UTC
### Expected behavior
In SonarQube, after selecting a project in combo and click in "Generate", a zip should be generated with a .docx, .md, .csv and a .xlsx
### Actual behavior
After clicking in "Generate", no report is generated.
It seams that, if project name contains any special char, no report is generated.
### Steps to reproduce behavior
Create a project with name containing special char, i.e.
SonarScanner.MSBuild.exe begin /k:"my-valid_project_key" /n:"My Valid: Project Name"
msbuild
SonarScanner.MSBuild.exe end
### Detection version
SonarQube............: 7.9.2.30863
SonarQube CNES Report: 3.1.0

**Comment by Sancretor** [comment] 2020-02-11 13:31
Hi @wilsade !

We were not able to reproduce your error.  
Can you provide us a projectKey that triggers this error, please ?

**Comment by wilsade** [comment] 2020-02-11 13:37
Hi @Sancretor .

Just define a project name with `:`, i.e:
SonarScanner.MSBuild.exe begin /k:"my-valid_project_key" /n:"My Valid: Project Name"

**Comment by Sancretor** [comment] 2020-02-11 15:06
I just tested to create a project with _my-valid_project_key_ as key, and _My Valid: Project Name_ as name, and I'm still able to generate a report...  
I don't have any Windows machine available, so maybe it's related to the platform but I can't say.  
  
I'll try to find one ...

**Comment by wilsade** [comment] 2020-02-11 16:39
I have a project key: "_demo";
Its name is: "_demo: Demonstracao";
Here is the generate report print:

![image](https://user-images.githubusercontent.com/14340865/74257379-82884300-4cd3-11ea-92c7-9862a591c844.png)

My generated zip file:

![image](https://user-images.githubusercontent.com/14340865/74257562-c7ac7500-4cd3-11ea-8ce4-b39e4976f3f9.png)

I am using Windows 10 pro, in portuguese.

Hope it helps.
Thanks,

**Comment by Sancretor** [comment] 2020-02-11 17:17
I finally found a Windows 10 laptop, and now I'm able to reproduce the issue, just like in your screenshot.  
It seems to be related with how Windows handles special characters in file names, because everything looks good on Linux.  
I can't say when we'll be able to correct that, but it's definitely an issue.  
  
Thanks again for your feedback !

**Comment by LePat** [comment] 2020-03-25 12:57
In the case of / (slash) in project name, the report will contain the / in it, it produces a "file not found" on linux host. I just modified the line 97: model.getProjectName() becomes model.getProjectName().replace("/", "_") to make it work.

**Comment by Sancretor** [comment] 2021-11-08 09:34
Hi !

We released the 4.0.0 version some time ago, with SQ 8.9 compatibility.
Did you try to use it ?
If so, did it solve the issue ?

**Comment by Sancretor** [comment] 2022-01-26 08:51
Without any news, I close this issue.
If anything related to special chars comes out again, we'll re-open it.

**Closed by Sancretor** 2022-01-26 08:51 UTC
Labels: bug
