### ISSUE TITLE
{"error":"This project can't be exported, please check your token."}

### ISSUE THREAD

**Issue by CaesarSopranus** [cnescatlab/sonar-cnes-report#97] opened 2019-11-05 15:28 UTC
Hi,
I was trying for the first time the plugin from the UI in a Windows 2016 sonarQube installation
but using it by UI i received this message:
{"error":"This project can't be exported, please check your token."} 
If i understood well the token is autogenerated with the name cnes-report so i tried the same token in standalone mode but the result is:

> SonarQube URL: http://localhost:9000
> SonarQube online: true
> Detected SonarQube version: 7.9.1
> [ERROR] Unauthorized error sent by SonarQube server (code 401), please provide a valid authentication token to cnesreport.

So i tried again standalone with a token i usually use and the error change:

> SonarQube URL: http://localhost:9000
> SonarQube online: true
> Detected SonarQube version: 7.9.1
> [ERROR] Unknown URL error sent by SonarQube server (code 404), please check cnesreport compatibility with your SonarQube server version.
[cnesreport-0.log](https://github.com/lequal/sonar-cnes-report/files/3809686/cnesreport-0.log)

[sonar.txt](https://github.com/lequal/sonar-cnes-report/files/3809735/sonar.txt)

Thanks
Regards,
Cesare

**Comment by muthukumarmanivel** [comment] 2019-11-13 12:45
I am also 
![image](https://user-images.githubusercontent.com/33922407/68764873-8c04ff00-0641-11ea-8952-b2a5eee43731.png)
facing the same error at sonarqube version 7.5

**Comment by Sancretor** [comment] 2019-12-04 15:27
Hi @CaesarSopranus & @muthukumarmanivel !  
  
Thanks for your feedback !  
Unfortunately, we are not able to reproduce your error...  
Can you please provide the full command line you used ?

**Comment by CaesarSopranus** [comment] 2019-12-04 15:53
Hi @Sancretor,
this is the command line used i kept it as simple as i can
![cnes_plugin_issue](https://user-images.githubusercontent.com/38726051/70157400-d19f6f80-16b5-11ea-9fc8-41c77017ab59.PNG)

Thanks
Cesare

**Comment by Sancretor** [comment] 2019-12-10 09:41
Hi @CaesarSopranus 

I just figured that you are working on Windows, and we never did any tests on this OS.
We will come back to you after testing it.

Thanks for your answer !

**Comment by asinkxcoswt** [comment] 2020-02-03 17:04
I got the same error message when trying to generate a report. My installation is on ubuntu 16.04. In my case it is likely because I use some special character in projectKey. It become working after I changed the projectKey to be a normal word.

**Comment by begarco** [comment] 2020-02-03 17:09
Hi @asinkxcoswt, could you please provide us a project key which make the plugin raise this error?

**Comment by Sancretor** [comment] 2020-02-11 17:24
@asinkxcoswt : your issue may be related to #107

**Comment by pangxeum** [comment] 2020-06-02 15:12
Hi there,
I have just installed through the Marketplace version 3.2.2 on SQ 7.9.2 running on Red Hat 7.7 and tried to generate a report for some pre-analysed projects. I'm getting
`{"error":"This project can't be exported, please check your token."}`
almost immediately for all of them.
What I might be doing wrong?
Thank you

**Comment by rtarasov** [comment] 2021-01-12 11:45
Hi Guys!
Experiencing absolutely same problem! Using SQ 8.5.1 and plugin version 3.2.2. @pangxeum how did you solve this problem?
Thank you

**Comment by pangxeum** [comment] 2021-01-12 14:00
Sorry, @rtarasov. We didn't solve it. We are now using other plugins that are more or less enough for us.

**Comment by abner** [comment] 2021-03-15 21:08
> Sorry, @rtarasov. We didn't solve it. We are now using other plugins that are more or less enough for us.

Do you mind to tell us which plugins are you using? Thanks in advance.

**Comment by BlackFrog1** [comment] 2021-03-16 16:01
@rtarasov @pangxeum Can you please recommend another plugin?  I have the same error.  Running SonarQube version 8.7 (build 41497).

**Comment by pangxeum** [comment] 2021-03-16 16:10
Hi @BlackFrog1 @abner 
We are using the Bitegarden Report Plugin For SonarQube. But, unfortunately, it is not free...

**Comment by sempervictus** [comment] 2021-08-23 20:48
Happening here as well - SQ 8.9 on Arch Linux

**Comment by Sancretor** [comment] 2021-11-08 09:31
Hi !

We released the 4.0.0 version some time ago, with SQ 8.9 compatibility.
Did you try to use it ?
If so, did it solve the issue ?
We completely change the way the plugin works so these errors should not happen anymore.

**Comment by Sancretor** [comment] 2022-01-26 08:51
Without any news, I close this issue.
If anything related happens again, we'll re-open it.

**Closed by Sancretor** 2022-01-26 08:51 UTC
Labels: bug, investigation, not reproduced
