### ISSUE TITLE
cnes report download without signing in with credentials. possible ?

### ISSUE THREAD

**Issue by inugravi** [cnescatlab/sonar-cnes-report#322] opened 2022-06-08 10:39 UTC
> _Before posting a new question, please read the README.md and check existing issues._

#### Describe what you need to know

Dear Star Team,

We have a setup in our organization where we are downloading the cnes report by signing into sonarqube portal with our credentials.  
Now the new requirement is that we want to download the report without signing into the portal because we can't grant **administrator** permission to everyone in team. Please help in achieving so.

**Comment by inugravi** [comment] 2022-06-09 05:19
Hi @Sancretor ,

Yes I want to download the report from the portal (not via command line) without signing into it.

In simple words
Our requirement is to visit our site for example www.star-sonarqube.com. 
Step-1:  Go to **More**option  
Step-2: Select **CNES Report** and 
Step-3: Select **Project** followed by **Branch** and then **Generate**.

However for our existing setup, after the Step-2 we need to login with our credentials. 
Our requirement is to bypass this login and directly download the report.

**Comment by Sancretor** [comment] 2022-06-10 15:43
Hi @inugravi 
I'll have a look into it, but not sure we can change this behaviour.
While using this plugin you may need some permissions, so logging in might be required by SonaQube.
I don't remember exactly how it works, so a little investigation before I come back with some news.

**Comment by inugravi** [comment] 2022-06-12 05:57
sure @Sancretor 

No problem. Please take your time :)

**Comment by inugravi** [comment] 2022-06-20 03:48
Hi @Sancretor 

Any update on this please.

**Comment by meghadadhich** [comment] 2022-06-23 06:29
Hi @Sancretor, 

Plugin is not allowing report download for any non admin users with read access. its failing with error.

**Comment by inugravi** [comment] 2022-06-23 06:35
> Hi @Sancretor,
> 
> Plugin is not allowing report download for any non admin users with read access. its failing with error.

Yes @Sancretor 
we don't want to by pass login to download cnes report. we just want to download for non admin users.

**Comment by Sancretor** [comment] 2022-06-23 14:54
Hi !

That's exactly what I understood :)
I tried to reproduce this, but even with a non-admin user but I actually can access the plugin page and generate a report so...
Are you sure the non-admin user has at least "browse" rights on the project you want to generate a report on ?
What error do you have when you try to access the plugin page / generate a report ?

Again, unfortunately, the part of the plugin code that handles the SonarQube plugin registration is *not* requiring admin privileges. So we're explicitly not requiring anything at all, and we probably can't override the behaviour you have because it is handled by SonarQube itself...

**Comment by Topin2001** [comment] 2024-07-11 08:04
Without any reponse, I'm closing this issue, feel free to ask me to re-open it if you encounter this issue again

**Closed by Topin2001** 2024-07-11 08:04 UTC
Labels: question
