### ISSUE TITLE
Not able to open the generated .docx file on version 7.9.3

### ISSUE THREAD

**Issue by rsbgithub** [cnescatlab/sonar-cnes-report#200] opened 2021-03-17 17:08 UTC
#### Describe what you need to know

I have two instances running Docker community edition 

- One is running SonarQube version: 7.0.0 
- Other one is running SonarQube version: 7.9.3

On both the instances I can access the UI and can see the runs and the reports/issues on the UI.

To get the reports i try to run 

`java -jar sonar-cnes-report.jar -p groupId:artifiactid ` on the instance running 7.0.0
I can get all the reports and the .docx works fine.

But when i run  the same 

`java -jar sonar-cnes-report.jar -p groupId:artifiactid`  on the instance running 7.9.3

I can get all the reports along with the docx file. I am able to open all the other generated report files (xlsx and csv) but i am not able to open the .docx file. It crashes on opening as if it is an invalid file. I can see that the generated .docx file has has a size of 54.9kb

I have tried using different versions of sonar-cnes-report.jar file , 2.2.0 and 3.3.0 also tried running it with Java version 8 and 11

#### User environment 

Red Hat Enterprise Linux Server 7.4 (Maipo)
SonarQube version: 7.0.0 is running on Java 8
SonarQube version: 7.9.3 is running on Java 11

Please advise.

**Comment by rsbgithub** [comment] 2021-03-17 17:43
Hi, thanks for your response. First i thought it might be a java 11 issue as i get the following warnings if i run the command with java 11
`SonarQube online: true
Detected SonarQube version: 7.9.3
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.apache.poi.openxml4j.util.ZipSecureFile$1 (file:/home/scripts/tmp/sonar-cnes-report.jar) to field java.io.FilterInputStream.in
WARNING: Please consider reporting this to the maintainers of org.apache.poi.openxml4j.util.ZipSecureFile$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Report generation: SUCCESS
`

But when i tried running the command again with java 11 and pointing to the 7.0.0 server. I do get the above warning but the reports are generated and i can open all the generated files along with the docx file

That , kind of suggested to me that the issue could be the sonar version and not the java version. 

I can also confirm that 
SonarQube version: 7.0.0 is running on Java 8
SonarQube version: 7.9.3  is running on Java 11

**Comment by rsbgithub** [comment] 2021-03-18 09:35
Hi @Sancretor,
> Do you have any issues/warnings reported inside your SonarQube logs that could related to that ?
Can you please advise which logs i should be looking into. When running this "java -jar  cnes " report generation. Does it log in any of the sonar logs.
Please advise
Regards

**Comment by Sancretor** [comment] 2021-03-18 11:02
Hi @rsbgithub 

I agree with you, the java version may not be the problem, because we are also using SonarQube Docker images as you do.
We have the very same versions and all is working fine. (these warnings are known)

In your SonarQube container, there must be some log files. As the tool is calling various APIs from SonarQube, there may be some errors showing that something went wrong.
Seeing your last message, I guess there is nothing useful in the command line tool output...

I really don't have a clue... but it might help if we could reproduce your issue.
The best thing would be to have the exact same SonarQube with the project data inside... but unfortunately, it's personal/private data so not possible.

Does this problem happen with all your SonarQube projects, or only this one ?

**Comment by rsbgithub** [comment] 2021-03-18 12:14
Hi @Sancretor,
I have tried and i can see the same issue on all the projects running on 7.9.3.33349.
Also i have checked the logs under all these section. When i run the "java -jar". I don't see any new log lines . I have also tried changing the level to debug.

![image](https://user-images.githubusercontent.com/3941918/111624158-3c10ec00-87e3-11eb-960a-fbe1ea4b45d1.png)

Thanks
Regards

**Comment by rsbgithub** [comment] 2021-03-18 13:49
Hi @Sancretor ,
Another thing i have noticed is that in docker access.log file for the two report generation runs, noticed that there are more lines for 7.9 than in 7.0. May be you might be knowing the reason for this. I have attached the extract.

[access.log - sonarqube:7.0-community.txt](https://github.com/cnescatlab/sonar-cnes-report/files/6164572/access.log.-.sonarqube.7.0-community.txt)
[access.log - sonarqube:7.9-community.txt](https://github.com/cnescatlab/sonar-cnes-report/files/6164573/access.log.-.sonarqube.7.9-community.txt)

**Comment by Sancretor** [comment] 2021-08-11 10:09
Hi @rsbgithub 

Sorry for the huge delay.
It's weird that executing the CNES report does not generate any new line of logs, because it should at least indicated it has worked successfully or not.
If you're using a Docker Image, you should have a look at what the command `docker logs` may return.
Could you please provide this output ?

**Comment by Sancretor** [comment] 2021-11-08 09:26
Hi @rsbgithub 

We released a new version of the plugin some time ago.
Did you try to use it ?
If so, did it solve your issue regarding docx generation ?

**Comment by Sancretor** [comment] 2022-01-26 08:59
Without any news, I close this issue.
If this problem happens again, we'll re-open it.

**Closed by Sancretor** 2022-01-26 08:59 UTC
Labels: question
