### ISSUE TITLE
The system cannnot find the path specified

### ISSUE THREAD

**Issue by namson0482** [cnescatlab/sonar-cnes-report#286] opened 2021-09-23 07:26 UTC
#### Describe the bug
It cannot create the output folder to store generated report files (bug happen on window os only, linux is fine - no bug). 

#### To reproduce

Step 1: java -jar sonar-cnes-report-3.3.1.jar -s https://code-quality.acb.com.vn -t f43fc769f4d29d418a42d82a857f32d8ce356f31 -p core-virtual-card-consumer_279 -l en_US -o d:/

Error console: [ERROR] d:\2021-09-23-core-banking\core-interfaces-api\core-virtual-card-consumer-analysis-report.docx (The system cannot find the path specified)

If I created an output folder before I execute the command then it runs ok. I mean If I created a folder such as: d:\2021-09-23-core-banking\core-interfaces-api

#### Expected behavior

It should create the output folder if the output folder doesn't exists 

#### Screenshots & log
![image](https://user-images.githubusercontent.com/2830607/134468800-6edd5ee9-a0db-464a-b4c3-f4c6695df876.png)

#### User environment 
* OS: Window 10
* Project version: sonar-cnes-report-3.3.1

**Comment by Sancretor** [comment] 2021-09-23 11:30
Hi @namson0482 
Thanks for the feedback.
Your issue seems related to #257, so it should be fixed with the next release (dev branch for now).
I'll make some tests to be sure.

**Comment by Sancretor** [comment] 2021-09-23 14:17
@namson0482 
Unfortunately, I'm not able to reproduce your error, using the exact same command.
The only way I get the same error is by adding the option "-c", which is related to #257 and fixed in the next release.

Are you sure you're using a JAR downloaded from our repo ? and not a fork from somewhere else ..?
Because you're using "-o d:/" and you expect an output dir named " d:\2021-09-23-core-banking\core-interfaces-api\" ... that's not how it works.

**Comment by namson0482** [comment] 2021-09-24 09:55
@Sancretor 
I go to your repo and download version 3.3.1 again and run it again. You can see image as per below
Step 1: 
java -jar sonar-cnes-report-3.3.1.jar -s https://code-quality.acb.com.vn -t f43fc769f4d29d418a42d82a857f32d8ce356f31 -p core-virtual-card-consumer_279 -l en_US -o .

###Screenshot
![image](https://user-images.githubusercontent.com/2830607/134652633-42841b26-41b4-4d55-b669-9ca6e9d0b14f.png)

### Another scenario
As you can see above. I still get an error. The system cannot find the path system specified.

Step 1: 
I created folder name with path system specified like: C:\Users\son.vu\Desktop\2021-09-24-core-banking. You can see image below

![image](https://user-images.githubusercontent.com/2830607/134655006-d60f43f0-4c42-4c48-8d6c-a1323c973073.png)

Step 2:
I executed command like (using one more option like -d at here) - It run ok: java -jar sonar-cnes-report-3.3.1.jar -s https://code-quality.acb.com.vn -t f43fc769f4d29d418a42d82a857f32d8ce356f31 -p core-virtual-card-consumer_279 -l en_US -d 2021-09-24 -o .

![image](https://user-images.githubusercontent.com/2830607/134655321-b5ea2fc7-1adc-493c-a9ea-7b0b1e5dec23.png)

Make sure I use jar file from your repo. My SonarQube instance only can run with version <= 3.3.1 that's why I do not try to test with version 4.0.0. If I run with version 4.0.0 then I get error like below:
![image](https://user-images.githubusercontent.com/2830607/134655996-e612f416-ec68-4033-aa00-5d79e3547baf.png)

Could you please let me know what big change are there in version 4.0.0? that cannot run with my instance SonarQube.

Thanks

**Comment by Sancretor** [comment] 2021-09-24 12:16
Hi @namson0482 

Thanks for the detailed answer, I'll look into it becasue I can't reproduce the anomaly. That's weird.
Do you use the SonarQube community edition ? Or developer ? Or higher ?

Regarding changes on 4.0.0, it's mainly SonarQube API changes which impacts the way our tool works.
Which is why we prevent it to work on non-compatible SonarQube versions (8.2.0 is not compatible, only 8.9 LTS).

**Comment by namson0482** [comment] 2021-09-24 13:25
Hi @Sancretor 
Currently, I use the SonarQube community edition. It only happened on window os. Linux OS is ok. I check with 3 computer that they are running Windows 10 and get the error like above.

**Comment by Sancretor** [comment] 2021-11-08 09:44
Hi @namson0482 
Sorry for the delay, but I still can't reproduce your issue...
Do you have anything new on your side ?

**Comment by Sancretor** [comment] 2022-01-26 09:02
Without any news, I close this issue.
If it happens again, we'll re-open it.

**Closed by Sancretor** 2022-01-26 09:02 UTC
Labels: bug
